### ISSUE TITLE
Water Sieve request

### ISSUE THREAD

**Issue by unmog** [Cairath/ONI-Mods#10]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Id like the Water Sieve to output at 30c instead of 40c

**Describe alternatives you've considered**
I'd be fine with either some information on how to do it myself, or if it's not too much to ask, if someone could make a quick mod for it? I've tried looking at the current Water Sieve mod to see if I could work it out myself, unfortunately Im not sure how to open dll files.

**Additional context**
I just think 40 is too hot, and 30 would be more convenient for bristle blossoms. I figure a small change like that shouldnt be too hard, but I admit not knowing where even to start.

Please and thankyou for your time :)

**Comment by Blindfold** [comment]
This probably could be achieved by means of BuildingModifier MOD by @javisar (https://github.com/javisar/ONI-Modloader-Mods/tree/master/Mods/BuildingModifier).

**Comment by javisar** [comment]
In this specific case, I don't think is possible to modify Water Sieve output temperature with BuildingModifier.

**Comment by Blindfold** [comment]
> In this specific case, I don't think is possible to modify Water Sieve output temperature with BuildingModifier.

Yeah, right. Just tried to write config for this change and realized that ElementConverter component is not stored as property of WaterPurifier.

**Comment by Blindfold** [comment]
... or it could be an opportunity to improve BuildingModifier even further ;)
(...gone codding...)

**Comment by unmog** [comment]
Thanks so much for looking into it for me! When I asked I figured it would be something easy to do but I guess thats what I get for my ignorance.

**Comment by javisar** [comment]
> ... or it could be an opportunity to improve BuildingModifier even further ;)
> (...gone codding...)

Sure!

**Comment by Cairath** [comment]
It is in fact very easy to do and doesn't need any other mods.

[Sieve30C.zip](https://github.com/Cairath/ONI-Mods/files/2740703/Sieve30C.zip)

I'm at work so a only a ghetto zip but there you go

**Comment by Cairath** [comment]
It is in fact very easy to do and does not need any additional mods.

[Sieve30C.zip](https://github.com/Cairath/ONI-Mods/files/2740713/Sieve30C.zip)

**Comment by javisar** [comment]
> It is in fact very easy to do and does not need any additional mods.
> 
> [Sieve30C.zip](https://github.com/Cairath/ONI-Mods/files/2740713/Sieve30C.zip)

Yes, it's easy, in fact i think both of us have similar mods: Your Water Sieve Dynamic Output  and my NoFixedTemps

**Comment by Cairath** [comment]
SInce this is resolved, let's move discussion about other mods somewhere more relevant please
