### ISSUE TITLE
Could you update Algae Grower & Flow Splitters to the latest game version?

### ISSUE THREAD

**Issue by vizthex123** [Cairath/ONI-Mods#100]
Title. Would be great to use them again, loved the mod.

**Comment by hilgner82** [comment]
Update to Harmony 2.0 is required
https://forums.kleientertainment.com/forums/topic/130712-oni-is-upgrading-to-harmony-20/

**Comment by Violist4Life** [comment]
Any chance of Flow Splitters being updated? Absolutely LOVE your mods and haven't been able to find any others like it.
