### ISSUE TITLE
Cobalt not included in metals valid for Refined Metals Usable As Raw Metals

### ISSUE THREAD

**Issue by theobserver12** [Cairath/ONI-Mods#101]
What it says on the tin, refined cobalt isn't usable in place of metal ore.
Thanks for the mod!

**Comment by Cairath** [comment]
Late on commenting, but fixed a few months ago!

**Comment by BayleafBeeen** [comment]
Hi there! Sorry to harp on this after it's already been closed, but I'm still to this day experiencing this. Refined Cobalt is still not showing up with the other metals when building, using the Steam version of the mod. I'm also using the mod updater mod, and have even tried the force update option on this mod, but it's still just not letting me use cobalt, so I'm not sure what else to do about it. Any chance of looking into this again?
