### ISSUE TITLE
Wireless Automation emitters work without power

### ISSUE THREAD

**Issue by modo-lv** [Cairath/ONI-Mods#102]
**Describe the bug**
Wireless Signal Emitter without power shows active animation and sends green signal to the receiver even while showing "No Power Wire Connected".

**To Reproduce**
1. Build a Wireless Signal Emitter and Receiver, set them to the same channel.
2. Do not connect the Emitter to any power source
3. Send a green signal to the Emitter
4. Emitter shows activity and Receiver receives the signal.

**Expected behavior**
No signals emitted without power.

**Screenshots**
![image](https://user-images.githubusercontent.com/731551/127497628-d7a694ce-bf0b-4142-8f5e-6314d991c477.png)
![image](https://user-images.githubusercontent.com/731551/127497688-72e7759c-1319-4b3b-a7aa-c06eb7fe59d4.png)

**Comment by modo-lv** [comment]
`Disabled` status seems to be ignored as well.

**Comment by Cairath** [comment]
Fixed -- please use Mod Updater if steam doesn't provide an update

**Comment by modo-lv** [comment]
Still works without power.
