### ISSUE TITLE
The latest game update made all the tile-build mods to crack 

### ISSUE THREAD

**Issue by Ventulus-lab** [Cairath/ONI-Mods#105]
Including Cairath's Marble Tile and Mosaic Tile，etc
I play the Vanilla game.
The mistake info：
Exception in RegisterBuilding for type MosaicTile
System.Missing FieldException:Field'BuildingDef.isSolidTile' not found.
at BuildingConfigManager.RegisterBuilding(IBuildingConfig config)

**Comment by Cairath** [comment]
Thanks for the info, uploaded the updated versions for the two mods.
