### ISSUE TITLE
Wireless Automation - ports issue since game update 483944 (Rad New Worlds)

### ISSUE THREAD

**Issue by HugePinball** [Cairath/ONI-Mods#107]
After the game update, it seems like some mod buildings had enable/disable automation ports added somehow.   With the wireless signal receivers this means they are forced to have overlapping ports and do not work and can no longer be built.

**Describe the bug**

**To Reproduce**
1. Run game after update 483944
2. Attempt to build a wireless signal receiver
3. Cannot build saying "Automation ports cannot overlap"

[https://i.imgur.com/4qjxNUF.jpg](https://i.imgur.com/4qjxNUF.jpg)

**Comment by kfishkin** [comment]
same here.

**Comment by Ixkik** [comment]
Me too.

**Comment by Cairath** [comment]
Fixed -- please use Mod Updater if steam doesn't provide an update
