### ISSUE TITLE
Automation Overlap

### ISSUE THREAD

**Issue by Seeker15438** [Cairath/ONI-Mods#109]
**Describe the bug**
Wireless Receiver Provides an error not allowing it to be placed in an open spot saying the automation cannot overlap.

**To Reproduce**
Unsure if there is anything to reproduce other than installing and using in a world.
This was also tested on other worlds as well.

**Expected behavior**
To be able to place the item in the world.

**Screenshots**
![Oxygen Not Included 14_11_2021 10_42_37 am](https://user-images.githubusercontent.com/53812998/141677864-fd0a17f1-e037-4636-89e2-c48aa73b7491.png)

**Additional context**
N/A

**Output log**
If applicable (game crashes or displays errors) please copy and paste part of the output_log.txt game file that contains information about the crash/error.
N/A

**Comment by jeff45674** [comment]
same issue I am having. completely broken and unusable.

**Comment by Cairath** [comment]
Fixed today -- please use Mod Updater if steam doesn't provide an update
