### ISSUE TITLE
Plan Buildings Without Materials: the building bar (left-bottom) is out of visible screen

### ISSUE THREAD

**Issue by mx2048** [Cairath/ONI-Mods#111]
**Describe the bug**
Plan Buildings Without Materials: the left-bottom bar is out of visible screen (see the screenshot)

**To Reproduce**
1. Start a new regular game.
2. Research at least one science project.
3. Restart the game.

**Expected behavior**
The base-oxygen-power-etc building bar should be aligned with the dig-cancel-deconstruct-etc bar.

**Screenshots**
![ONI-bug](https://user-images.githubusercontent.com/24634074/143732082-16fcdad6-6b85-4d5d-951d-bc638888cb90.jpg)

**Comment by Cairath** [comment]
This is a base game bug. You can reduce your UI scale to 99%.

**Comment by mx2048** [comment]
I reduced the UI scale to 90% and the bug still persists (see screenshot). 
I am quite sure something in the mod interferes with the game UI. When disabled, everything works fine. When enabled, the UI is shifted. Tested multiple times.
![bandicam 2021-11-28 14-15-18-560](https://user-images.githubusercontent.com/24634074/143788220-7e742ccf-8316-44f0-818e-bc759ba6d4b8.jpg)
