### ISSUE TITLE
Bottom buttons move a bit offscreen on enabling mod "Plan Buildings Without Materials"

### ISSUE THREAD

**Issue by n-epifanov** [Cairath/ONI-Mods#112]
**Describe the bug**
Bottom button text gets offscreen

**To Reproduce**

Enable mod on up-to-date vanilla game, buttons move down.

**Screenshots**

![Oxygen Not Included](https://user-images.githubusercontent.com/217547/146443991-69f99899-110c-49cf-bb68-9905b6b73888.png)
![2](https://user-images.githubusercontent.com/217547/146444153-50216f02-3dfa-48b7-af60-78dd22d4834a.png)

**Comment by Cairath** [comment]
I forgot to respond to this, but it turned out to be a base game issue.
