### ISSUE TITLE
Outdated mods

### ISSUE THREAD

**Issue by ErikBrendel** [Cairath/ONI-Mods#114]
Hey! I enjoyed playing with your Bigger Camera Zoom Out mod. Recently, the game states that it is "outdated" and cannot be used anymore (I am playing the game via steam, without the spaced out extension, on Windows 10, no other mods installed except the German language pack).

I have heard that it has something to do with the upgrade of "Harmony". Do you plan on doing this? That would be cool

Yours
A fan :)

**Comment by Cairath** [comment]
Hey, please download and use mod called "Mod Updater" in the workshop. Steam very often has issues delivering the most recent version. The zoom mod is up to date and the game should figure it out after you use the updater

**Comment by Old-Hunter-Dempsey** [comment]
Do you plan on updating your Flow spliters mod? I'm in dire need of it.
