### ISSUE TITLE
Achievement progress crash on Spaced Out!: MissingFieldException: Field 'Components.PlantablePlots' not found

### ISSUE THREAD

**Issue by FrancoisDupayrat** [Cairath/ONI-Mods#118]
When trying to open Achievement progress via the menu, the game crash with the exception:
`MissingFieldException: Field 'Components.PlantablePlots' not found`

It seems to come from the `foreach (var plantablePlot in Components.PlantablePlots.Items)` line in AchievementProgressScreen.cs.

Game version: U40-494396-5

**Comment by grumpytm** [comment]
This happens in normal (got the DLC but it's not enabled) game as well.

**Comment by rgarcia7** [comment]
Same here, I have DLC enabled
And crashes with the same exception when Achievement progress is enabled

Game version: U41-498381-5

**Comment by Cairath** [comment]
the mod  has been deprecated due to the in-game tracker being decent now
