### ISSUE TITLE
Marble Tile bugged

### ISSUE THREAD

**Issue by Hasufel1** [Cairath/ONI-Mods#119]
The marble tile isn't available anymore in the building menu nor the copy button. It was available, I constructed some, then i putted the game in pause and when i leaved the pause, it was just disappeared, without any crash, any error message nor anything. It just disappeared. The mod is still on, the recipe is still in the reasearch menu, all the tile allready constructed are still in place, it is just impossible to create new ones. 

Don't know how to reproduce beacause i didn't do anything to make it happen. 
I didn't make any update or anything. I didn't even leave the game. I was playing, just putted the game in pause (with game menu open), then i went to take a nap, and when I unpaused the game, the marble tile was gone from the building menu. 

I tried everything, uninstalled all my mods, de-subscribe, re-subsribe, started a new game with only that one mod, nothing fixed, marble tile still appear in the research tree but not available to be construct in the menu. 

Ty for your mods, they are amazing!^^

![marble tile bug](https://user-images.githubusercontent.com/2060742/155850489-fe9d5a9b-f2ac-4392-8072-2a2cf5192423.jpg)
![marble tile research](https://user-images.githubusercontent.com/2060742/155850491-c9f8446f-d503-48b6-82fd-da32e16b92fa.jpg)

**Comment by duviebourg** [comment]
Hello, i have same issue with Wallpaper Mod,

Player.log outpout:

[11:29:17.961] [1] [INFO] Loading MOD dll: Wallpaper.dll
[11:29:17.963] <<-- CaiLib -->> Loaded [ Wallpaper ] with version 2021.7.1.1
[11:29:17.963] [1] [INFO] C:/Users/UserName/Documents/Klei/OxygenNotIncluded/mods/Steam/1717534457\Config.json
[11:29:17.963] <<-- Wallpaper -->> Failed to read config file Config.json with exception: Could not find file "C:\Users\UserName\Documents\Klei\OxygenNotIncluded\mods\Steam\1717534457\Config.json"
[11:29:17.964] <<-- Wallpaper -->> C:\Users\UserName\Documents\Klei\OxygenNotIncluded\mods\Steam\1717534457

**Comment by MayonnaiseJane** [comment]
According to the Klei forums, mods that aren't using their preferred way of adding buildings to the menu are broken till they switch to that method of adding buildings to the menu and they intended that in the latest update. Someone reporting this problem with most of their mod-buildings got this reply in the close note on their bug report:

"Mods using our supported ModUtil.AddBuildingToPlanScreen to add buildings are unaffected."

https://forums.kleientertainment.com/klei-bug-tracker/oni/missing-mod-build-items-in-menu-r34127/?tab=comments#comment-51657

**Comment by Cairath** [comment]
I am aware. Will be updated when I  have the time.
