### ISSUE TITLE
ONI crash when trying to upload

### ISSUE THREAD

**Issue by AndreasBroager** [Cairath/ONI-Mods#12]
**Describe the bug**
ONI crashes when clicking on the "Upload" for the tools not included mod.

**To Reproduce**
1. Verified local files with steam
2. Create a new game
3. Click upload
4. ONI freezes for 2-3 sec then crashes hard.

**Output log**

[oniCrash.txt](https://github.com/Cairath/ONI-Mods/files/2797668/oniCrash.txt)

**Comment by AndreasBroager** [comment]
[Serene.zip](https://github.com/Cairath/ONI-Mods/files/2797692/Serene.zip)
And here is the save game, if that might help. But I have tried with 3-4 new games. Both sandbox and non-sandbox. But same result every time.

**Comment by Cairath** [comment]
Is that iOS? I've heard of several people having issues on a mac, unfortunately I don't have anything of apple's that I could troubleshoot on :(

**Comment by AndreasBroager** [comment]
Yeah. It's on macOS.

**Comment by Cairath** [comment]
Hey,

sorry for the delay, I'm trying to get someone with a mac to help troubleshooting. Will get back once I  have some new info
