### ISSUE TITLE
4 more mod down - Wallpaper - Decors Light - Steel Lader - Buildable POI Props

### ISSUE THREAD

**Issue by duviebourg** [Cairath/ONI-Mods#120]
**Describe the bug**
Like [Hasufel1] issue 4 more [Cairath] Mod are down - It's worked perfectly Yesterday
 - Wallpaper
 - Decors Light
 - Steel Lader
 - Buildable POI Props

Item not aviable in build Menu but Present in Thech Tree.
Trying to remove all mod and test it one by one with Full Game re-installation and new Clear SandBox Session d'ont solve it.

Other Mod from other contributor have same issue
May Be the last minor patch update cause it ???
=> https://steamcommunity.com/games/457140/announcements/detail/3106925126799393639

Screen Shoot : 
![image](https://user-images.githubusercontent.com/100517021/155888103-fc565583-9c56-4f7c-9411-e74687b09401.png)
Steel Ladder isn't aviable in build menu (sand-Box activated)

![image](https://user-images.githubusercontent.com/100517021/155888145-78ad5de4-33ed-4194-b237-7c2dad38ed58.png)
But prensent in Thec Tree

**Comment by Cairath** [comment]
I am aware. Will be updated when I  have the time.

**Comment by porisius** [comment]
Only adding to the troubleshooting:

Wallpaper will work/build if used with the Blueprints mod. However, it is not able to be queued/selected manually.

I understand the time thing, so don't rush. Just hoping to have helped.

**Comment by porisius** [comment]
Devs made an update, @duviebourg, re-check the mods. The Wallpaper mod is functional.
