### ISSUE TITLE
No compatible mod found

### ISSUE THREAD

**Issue by LordButtah** [Cairath/ONI-Mods#121]
![Screenshot (9)](https://user-images.githubusercontent.com/100817378/156484822-33f278db-ecb4-4df4-a9e6-f10e8188d998.png)
I've downloaded the latest versions Geyser average output and Bigger Camera zoomout but for some reason can't get to activate inside the game. Thought I was doing something wrong so I downloaded a couple others namely "Wireless Automation" but I can get it work just fine. 
Have the average output and Bigger zoomout not being updated for DLC?

**Comment by Cairath** [comment]
They are. Use "Mod Updater" mod

**Comment by LordButtah** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/100817378/156690013-65e35703-0388-42f9-8689-3760b1a72865.png)
I tried the suggestion but it's the same result. Also tried deleting all mods and then "verify integrity of game files" from steam but no luck. Any suggestions?
