### ISSUE TITLE
"Plan Buildings Without Materials" Messes Up Building UI Buttons, Specifically When...

### ISSUE THREAD

**Issue by Wyrdhare** [Cairath/ONI-Mods#122]
**Describe the bug**
Building UI components becomes misaligned, more obviously when there are uninitiated research trees existing on the save game. I believe that it may be the UI animation getting stuck. The buttons end up in a position where they become more difficult to click on if a menu is already open.
I have been able to correct the issue in-game by enabling and disabling Sandbox Mode, but if you don't want to use Sandbox Mode, you're out of luck.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable the "Plan Buildings Without Materials" mod
2. Start a new game OR load a saved game.
4. See "error"

Steps to demonstrate temporary fix:
1. Enable the "Plan Buildings Without Materials" mod
2. Start a new game OR load a saved game.
4. Enable "Enable sandbox tools" in Game Options
5. Toggle "Sandbox Mode" on
6. Toggle "Sandbox Mode" off
7. Repeat, until issue is fixed

**Expected behavior**
The user interface is supposed to be "normal".

**Screenshots**
Screenshots attached.

Abnormality:
![oni_buildwomat_mod_bug_1](https://user-images.githubusercontent.com/101028195/156906436-442bf987-b085-4abf-85e2-4d73e3d8d787.png)

Abnormality w/ Menu Open:
![oni_buildwomat_mod_bug_2](https://user-images.githubusercontent.com/101028195/156906438-3e088e89-f711-443f-812c-3ae003661101.png)

How It Should Look:
![oni_buildwomat_mod_bug_3](https://user-images.githubusercontent.com/101028195/156906999-5e1b1618-4f7d-4aae-b4a5-4d7da1623563.png)

**Additional context**
None

**Output log**
None

**Comment by Catsbuggy** [comment]
same trouble for me
https://prnt.sc/_s0H3bzb75hJ

**Comment by Las7ime** [comment]
Same trouble，My temporary solution
Modify，settings - graphics - UI-zoom

**Comment by Cairath** [comment]
A bit old, but that's a base game problem and occurs without the mod installed too.
