### ISSUE TITLE
Debug Does Not Discover Map not working after update

### ISSUE THREAD

**Issue by vincent-lu** [Cairath/ONI-Mods#123]
Using this version `2021.7.1.1`, but when using Debug mode it reveal the whole map (sometimes even other asteroids)

Mostly broken by recent Klei update.

**Comment by Jemsterr** [comment]
Confirming this is broken on Base Game, too.

**Comment by AlbertNewton** [comment]
Still doesn't work in Spaced Out

**Comment by Cairath** [comment]
updated on steam
