### ISSUE TITLE
On screen zoom buttons

### ISSUE THREAD

**Issue by bta908** [Cairath/ONI-Mods#124]
1)Is your feature request related to a problem? Please describe.

I like to play my games on remote play on my phone and and also on track pad. I cant use the scroll funchen to zoom in and out of areas. it would be nice if i had on screen bottons to click that i can use to do this.

2)Describe the solution you'd like

it would be nice if i had on screen bottons to click that i can use to do this.

3)Describe alternatives you've considered

i looked on the steam market place and looks like there nothing out there for this problom.

**Comment by Cairath** [comment]
Unfortunately I am not planning on adding such feature.
