### ISSUE TITLE
Is "Bigger Building Menu" still working?

### ISSUE THREAD

**Issue by vincent-lu** [Cairath/ONI-Mods#126]
Hi this mod doesn't seem to modify the height of menus in my games. I can set the height to 8 or 5 in Config.json and the menu height in game is always the same (about 6 rows?)

Perhaps it has something to do with my Graphic settings? (my settings is 5120x2160px Resolution at 130% UI Scale).

Thanks @Cairath for the hard work.

**Comment by mmseng** [comment]
Same here, Tried with and without a Config.json and the building menu is always at 6 items high. I appear to have the latest version (2021.7.1.1). My res is 2560x1440, UI scale at 110%.

I use several of Cairath's other mods and they all work great, so yeah thanks for that.

**Comment by aki-art** [comment]
This mod is modifying a field that no longer exists, and silent fails.
`buildGrid_maxRowsBeforeScroll` is no longer a thing, it has been probably changed to a constant instead, my compiler shows it as hard coded value of 6.

**Comment by Cairath** [comment]
I was actually sure I updated it with the last round of updates, but apparently I forgot. Pushed an update.

**Comment by LokyStaz** [comment]
It still doesn't work... Check the upper message from aki-art !
I didn't say outdated, but deprecated...
(Unless you find a new way to make it work, in that case i'm sorry cause it would mean that it doesn't work for another reason)

**Comment by Cairath** [comment]
Use Mod Updater, check the game loads proper version starting with 2022.11. If it was deprecated I'd have marked it as such.

And stop with all the !!!!!! or I'll block you, I don't need needless yelling here.
