### ISSUE TITLE
Dev Questions

### ISSUE THREAD

**Issue by lfricken** [Cairath/ONI-Mods#13]
Let me know if I should post this somewhere else.

Is there a list of animation names? For instance, you define the AlgeaGrower as anim: "algaefarm_kanim". Where did you get that string? I examined some asset files with a hex editor and found some, but it's not a very clean list.

Is there an Oxygen Not Included developer hub somewhere with all this info on it?

**Comment by Cairath** [comment]
Hey,

you don't really need hex editors for dealing with files - there are unity asset extractors such as Asset Studio which I use. There is no dev hub nor any full list of those - but with an extractor you can see a full list of anims available in the game.

With dev related questions please hit me up on my discord: https://discord.gg/7wNFaVd

**Comment by lfricken** [comment]
Has anyone considered opening a new set of pages on [the ONI wiki](https://oxygennotincluded.gamepedia.com/Oxygen_Not_Included_Wiki)?
