### ISSUE TITLE
wallpaper tiles not working[not changing color]

### ISSUE THREAD

**Issue by tonimark** [Cairath/ONI-Mods#133]
**Describe the bug**
when the wallpapers mod is installed the background tiles don't change color as they should and stay the same white color
**To Reproduce**
1. start a creative save with a sandbox
2. place down drywalls and try several materials
3. see error , no coloring

**Expected behavior**
the drywall would be colored as intended
**Screenshots**

**Additional context**

**Output log**
If applicable (game crashes or displays errors) please copy and paste part of the output_log.txt game file that contains information about the crash/error.
[Player.log](https://github.com/Cairath/ONI-Mods/files/9053818/Player.log)
[output_log.txt](https://github.com/Cairath/ONI-Mods/files/9053819/output_log.txt)
(output.log is outdated)

**Comment by aki-art** [comment]
Wallpapers don't color dry walls, they are a separate new building in the Furniture menu

**Comment by Cairath** [comment]
What Aki said.
