### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by ElectronicsArchiver** [Cairath/ONI-Mods#137]
<br>
<br>

<div align = center>

I've found that multiple GitHub ONI mod repositories 
were describing how to manually install mods, 
so I made a guide instead.

[Installation Guide]

Would you mind if I made a PR, replacing the 
two lines of instructions with a link to the guide?

</div>

<br>
<br>

[Installation Guide]: https://github.com/OpenModding/Installation/tree/main/Games/Oxygen%20Not%20Included

**Comment by Cairath** [comment]
Hey, no, i gain nothing from that, other than having to monitor what's on the other end

**Comment by ElectronicsArchiver** [comment]
Would you mind me refactoring your instructions then?
