### ISSUE TITLE
New update broke the algae grower

### ISSUE THREAD

**Issue by 4Donic** [Cairath/ONI-Mods#141]
**Describe the bug**
New update broke the algae grower mod

**To Reproduce**
Start the game

**Screenshots**
https://i.imgur.com/umhyxZq.png

**Output log**
If applicable (game crashes or displays errors) please copy and paste part of the output_log.txt game file that contains information about the crash/error.

**Comment by Cairath** [comment]
am aware, will provide an update within a few days

**Comment by Cairath** [comment]
update pushed to steam, remember to use Mod Updater if steam does not update it correctly
