### ISSUE TITLE
Yesterdays update broke the steel ladder

### ISSUE THREAD

**Issue by everac99** [Cairath/ONI-Mods#142]
**Describe the bug**
Update released has broken the steel ladder (game will crash on start)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Output log**
If applicable (game crashes or displays errors) please copy and paste part of the output_log.txt game file that contains information about the crash/error.

**Comment by Sergadra** [comment]
Can't support this. No crashes here check for other incompabilitys and post your logs.
Pressing play also does also not crash the Game.

**Comment by Cairath** [comment]
While it worked, an update fixing its position in the build menu has been pushed today.
