### ISSUE TITLE
Translation files request

### ISSUE THREAD

**Issue by cwt9527** [Cairath/ONI-Mods#148]
Hey, is there a way for me to make a translation of this mod? It'll be a pleasure to make one for my native language Simplified Chinese, cuz i'd already use the in game translation,Or I can provide you with Chinese translation
Love this mods
Thx

**Comment by cwt9527** [comment]
Plz~~~~~~

**Comment by Cairath** [comment]
I currently have no time to add translations to mods, and I do not allow reuploads. Sorry.
