### ISSUE TITLE
Enabling Lights Out is crashing game

### ISSUE THREAD

**Issue by engineer-pearl** [Cairath/ONI-Mods#149]
**Describe the bug**
Lights Out mod crashing game - Spaced Out DLC

**To Reproduce**
* Create a game
* Enable Lights Out mod
* Start Game
* Allow time to pass

**Expected behavior**
I should be able to play the Lights Out Game

**Actual Behavior**
The game crashes

**Output log**
If applicable (game crashes or displays errors) please copy and paste part of the output_log.txt game file that contains information about the crash/error.

```
MissingMethodException: !4 StateMachine`4/Parameter`1.Set(!4,!1)

BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <c775f779c2e74519bbe6a3fcac766187>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <c775f779c2e74519bbe6a3fcac766187>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <c775f779c2e74519bbe6a3fcac766187>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <c775f779c2e74519bbe6a3fcac766187>:0)
Game.SimEveryTick (System.Single dt) (at <22b78e98e912445f80b07998c97c06d8>:0)
Game.Update () (at <22b78e98e912445f80b07998c97c06d8>:0)

Build: U43-526946-S
```

**Comment by athpon** [comment]
I've this error too.
![image](https://user-images.githubusercontent.com/33125578/197453371-fe34a2e3-149a-40a1-b044-13e011a68425.png)
[Player.log](https://github.com/Cairath/ONI-Mods/files/9848943/Player.log)

**Comment by cpypcy** [comment]
Yep same problem here, it keeps crashing.

**Comment by Evil2056** [comment]
This was posted already, but for some reason, the mod author closed it. It's been a very long time with no updates that I can find. I know why it's not working, but not how to fix it.

**Comment by Cairath** [comment]
Because i was sick of people commenting non stop. I know it's broken, i said it's gonna be done when its done, and people keep commenting weird workarounds that don't work. I've got a damn life too and at this point i don't even feel like adding any improvements to the mod.

So, it's gonna be done when it's done and I'm going to be removing any further posts about it. One was enough.

**Comment by cpypcy** [comment]
If you had enabled comments on steam workshop and just drop message I know it's broken hold on I wouldn't have to go to github to ask for it.

**Comment by engineer-pearl** [comment]
In fairness to me, I did check to see if the issue had already been reported. I missed the relevant issue because it had been closed, preventing it from showing up in the search.
