### ISSUE TITLE
Decor lights mod

### ISSUE THREAD

**Issue by Drseps** [Cairath/ONI-Mods#155]
**Describe the bug**
in the decor lights mod the lights today stopped having the usual spread. specifically the Tile light, LED light, and Ceiling lght. 

**To Reproduce**
seems to do it even though I used the mod updater and have restarted the game

**Expected behavior**
The lights have a tile spread that they had been using, last normal look was about a week ago.
**Output log**
If applicable (game crashes or displays errors) please copy and paste part of the output_log.txt game file that contains information about the crash/error.

**Comment by Cairath** [comment]
Hey - that's Expanded Lights by Sky, not Decor Lights.
