### ISSUE TITLE
Refined Metals causes start-crash in Oxygen Not Included

### ISSUE THREAD

**Issue by Senacharim** [Cairath/ONI-Mods#156]
**Describe the bug**
Refined Metals causes start-crash in Oxygen Not Included

**To Reproduce**
Subscribe to 'Refined Metals Usable As Raw Metals' mod on Steam Workshop.  Start 'Oxygen Not Included' using Steam.  Observe crash.

**Expected behavior**
Ideally, this bug would not occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/9025459/209480768-699dd344-e056-4cee-b2ce-37145e2b19f3.png)

**Additional context**
This is one of my favorite mods.

**Output log**
Attached screenshot of error with details, and output log to assist with troubleshooting and fixing.

[Player.log](https://github.com/Cairath/ONI-Mods/files/10300580/Player.log)

**Comment by Cairath** [comment]
This is an issue with steam, not with the mod. Try verifying game files on steam, it seems that something got corrupted and verification usually fixes it. If it doesnt, can also try removing the folder its complaining about, but with such corruptions sometimes I had to just reinstall the game.

**Comment by Senacharim** [comment]
For completeness - verify files said "all file verified" with no errors.

'Mod Updater' caused the same crash - so no-go on that solution.

Uninstall and reinstall (followed by subsequent re-pull of subscribed mods by Oxygen Not Included) appears to have corrected the issue.  Thank you for you help.
