### ISSUE TITLE
Palmera Tree crashes the game after Quality Of Life 2023 update

### ISSUE THREAD

**Issue by 03GuB** [Cairath/ONI-Mods#160]
it just randomly crashes the game you dont even need to do anything specific 

[Player.log](https://github.com/Cairath/ONI-Mods/files/10833732/Player.log)

**Comment by Cairath** [comment]
Hey, I confirmed this happens specifically when the plant dies (like in your log). I'll try to find some time to look at it this weekend.

**Comment by Cairath** [comment]
Turned out to just need recompilation. I uploaded a new version on steam.
