### ISSUE TITLE
Epic Launcher Users

### ISSUE THREAD

**Issue by ShaCraft** [Cairath/ONI-Mods#17]
**Is your feature request related to a problem? Please describe.**
Are you planing on making the .Dll files available for Epic Launcher users? I did not know that buying the game on the epic store would limit mod use when I bought the game. I see some Mod creators have compiled versions here on github and as far as we (Epic users) are limited to only using those. I looked for a mod loader that would use my steam info to download the mods but I have not found a work around. Your mods look amazing and I would love to use them in my game play. Thanks for any info or advice you may have.
Sha

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Cairath** [comment]
Currently compiled executables are available here: https://static.toolsnotincluded.net/Mods.zip
I used to have compiled dlls in the repository but people would always not update and then complain about stuff that's been fixed... so I have to figure out some update-prompt for off-steam mods.

**Comment by ShaCraft** [comment]
Hey thanks so much! That was just what I was looking for. I'm not sure why but I can use a steam downloader for most mods but yours never return a .dll just a weird no extension file. On a side not Epic users don't have to deal with mods being updated and being forced to download so no restart bug. Tho we do have to track the mods for updates. I guess it has its pros and cons not being on steam. Thanks for the link mate! I'm excited to play and check out your fine handy work. 
=S=
