### ISSUE TITLE
Wallpaper Mod on Steam not working

### ISSUE THREAD

**Issue by Guinaro** [Cairath/ONI-Mods#18]
I wanted to start decorating my Great Hall with Wallpaper, but could not find it in my utilities building menu. I looked up the description which said it is researched in Home Luxuries, but although I researched that item. No mention of Wallpaper is made. 
I assumed a mod incompatibility and disabled all my mods but the Wallpaper one, reloaded my save game and still no mention regarding wallpaper.

**Comment by Cairath** [comment]
The mod itself certainly works, but with the steam shenanigans check if it actually has files in the folder
...\mods\steam\1717534457   -- if there are files here, delete the folder to force the game to re-download it

**Comment by Guinaro** [comment]
OK. Due to many mods adding items I completely overlooked the following fact: Wallpaper is apparantly researched in Artistic Expression and is in the Building Tab of Furniture (for me completely at the bottom of a very long list). This was the same when I started a new game with only this mod enabled. Made it easier for me to spot the wallpaper (drywall icon) in the research tab.

If this is the expected behavior, it would be best that the description on the Steam Page is altered.
