### ISSUE TITLE
ONI v364722 updated affected mod list

### ISSUE THREAD

**Issue by LazyZhu** [Cairath/ONI-Mods#20]
ONI v364722 changelog which about mods:
~~~
Mod should supply an 'anim' directory structured like our 'game/Assets/anim' directory. 
The game will look for a *_anim.bytes, *_build.bytes, and *.pngs for textures. The folder name dictates the animation name. If an existing animation is modded, the one in game is replaced; otherwise a new animation is added.
~~~

@Cairath's affected mods list:

1703606095_algae_grower
https://steamcommunity.com/sharedfiles/filedetails/?id=1703606095

1706142008_mosaic_tile
https://steamcommunity.com/sharedfiles/filedetails/?id=1706142008

1708810461_fervine
https://steamcommunity.com/sharedfiles/filedetails/?id=1708810461

1708823360_flow_splitters
https://steamcommunity.com/sharedfiles/filedetails/?id=1708823360

1714517353_ranching_sensors
https://steamcommunity.com/sharedfiles/filedetails/?id=1714517353

1718226085_wireless_automation
https://steamcommunity.com/sharedfiles/filedetails/?id=1718226085

1738906344_conveyor_rail_filter
https://steamcommunity.com/sharedfiles/filedetails/?id=1738906344

1823182964_palmera_tree
https://steamcommunity.com/sharedfiles/filedetails/?id=1823182964

**Comment by Cairath** [comment]
Updates will be ready when they're ready. If people keep nudging me about it non stop I'll spend the entire time responding instead of updating.

**Comment by LazyZhu** [comment]
This is the mod list cause game crash, and should be unsubscribed before they got updated. 
I made the list just for people who don't know the crash reason, not nudging you about it :)
