### ISSUE TITLE
the mod gets disabled and disable all mods when enabled 

### ISSUE THREAD

**Issue by tonimark** [Cairath/ONI-Mods#21]
**Describe the bug**
when I enable the mod and restart the game both this  mod and other installed mods get disabled by the game

**To Reproduce**
1. install the mod
2. enable the mod and restart

**Expected behavior**
the mod would work normally

**Screenshots**
nope

**Additional context**
nope

**Output log**
If applicable (game crashes or displays errors) please copy and paste part of the output_log.txt game file that contains information about the crash/error.
[output_log.txt](https://github.com/Cairath/ONI-Mods/files/3578491/output_log.txt)

**Comment by Cairath** [comment]
Game received an update yesterday that broke some mods. New versions were just uploaded to steam.
