### ISSUE TITLE
Enable All Mods: Suggest "Enable last known good"

### ISSUE THREAD

**Issue by ErzengelLichtes** [Cairath/ONI-Mods#22]
When trying to find out which mods are broken, I would enable a couple mods and restart the game. If it works, I'll enable more and restart. At this point, if it fails ONI will color the last-known-good mods as pink while the might-be-bad mods remain colored red. I then have to select the last-known-good mods and skip the ones that failed. 
"Enable All" is great, but for finding which mods are broken a "Enable Known Good" button that *only* enables the ones that are white or pink would be very helpful as well.

**Comment by Cairath** [comment]
This is something I can consider for my in-progress mod manager. I'll leave it up as a suggestion.
