### ISSUE TITLE
Please balance mosaic and marble tiles!

### ISSUE THREAD

**Issue by PsychoXIVI** [Cairath/ONI-Mods#24]
This should be nerfed, since just simple floor of these allow to get maximum 120 decor, because of high 15 decor and on top of that, 3 tile radius. This is ridiculous - so unbalanced, so cheap... Even vanilla carpet tiles have 10 decor and 1 radius - and these are good...

I would love to have nerfed these to like 10 decor and 1 radius at least.

**Comment by Cairath** [comment]
Decor is like with metal tiles. This will not be changed.

**Comment by PsychoXIVI** [comment]
For those who want to change it anyway:
a) recompile the mods,
b) use `dnSpy` tool to change values without Visual Studio and compilation.
