### ISSUE TITLE
Refined Metals Usable As Raw Metals

### ISSUE THREAD

**Issue by Xuhybrid** [Cairath/ONI-Mods#25]
I'm just being pedantic but is there anything you can do about the material ordering? Either refined metals at the end, or raw before refined in pairs. It's harder to parse when it goes "raw copper, refined copper, refined iron, raw iron, raw wolframite, refined wolframite, refined gold, raw gold" for example.

**Comment by Cairath** [comment]
It could cause incompatibilities with mods that edit the resources screen - I'd rather keep it as simple as possible.
