### ISSUE TITLE
Plan Buildings Without Materials not working

### ISSUE THREAD

**Issue by skrysmanski** [Cairath/ONI-Mods#34]
**Describe the bug**
I've just installed "Plan Buildings Without Materials" but it doesn't work - or at least I can't figure out how to get it working.

**To Reproduce**

1. Have no plastic (but have plastic discovered)
2. Try to "build" a Mini Liquid Pump

**Expected behavior**
I'd expect that I can plan buildings without materials ;)

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/914747/65834516-ffde8880-e2db-11e9-9de9-870ef4047845.jpg)

**Additional context**
It's not a new game but an existing one.

I'm running ONI LU-366134.

**Comment by seona13** [comment]
If you don't have enough material to place even one, then the game doesn't auto-select. If you explicitly click "plastic", you should then be able to build as expected.

**Comment by skrysmanski** [comment]
@seona13 You're absolutely right. That did it for me.
