### ISSUE TITLE
About "Light out"

### ISSUE THREAD

**Issue by goxlove** [Cairath/ONI-Mods#35]
**Describe the bug**
Hello.
After installing this mod, I went out into space, and when I went to install the bunker door at midday, I get an error.
In "C: \ Users \ Username \ AppData \ LocalLow \ Klei \ Oxygen Not Included", and When I searched for "output_log.txt", I found no null data, I don't know what's wrong as well.

I leave you a screenshot with the file "output_log" in case of an error.
Thank you!
[output_log.txt](https://github.com/Cairath/ONI-Mods/files/3679515/output_log.txt)
![에러발생](https://user-images.githubusercontent.com/56060740/66018876-d14ef080-e51b-11e9-9ce0-4076e00cfee4.png)

**Comment by Cairath** [comment]
Hello,

The culprit is "smoother lights" - that mod is messed up and does not handle lights reaching out of bounds of the world - and the dupe got close enough for his headlight to be in the red out of world zone. If you remove smoother lights it should work just fine.

Cheers
