### ISSUE TITLE
Fervine opens and closes every few seconds

### ISSUE THREAD

**Issue by Noroji** [Cairath/ONI-Mods#42]
**Describe the bug**
Since the Launch Update (or an other fix between this and Recreation) Fervine started to open and close every other second even when in rooms that are not its ideal temperature. I tested it in areas above and below 20°C and had either opening and closing problems or the plant would stop opening at all after some time of playing.

**To Reproduce**
1.  Plant Fervine in newest update
2. Wait some seconds for it to start glowing
3. Watch it open and close all day long
4. Watch it not open anymore at all

**Expected behavior**
Should be opened and glowing as long as the plants Body Temperature is fine and the air around it is not at 20°C

**Screenshots**
Gifs of showing both behaviours. Forgot to show the temp around it in the "closed" fervine, but it was at the same temp at that moment.

[Album Link](https://imgur.com/a/7lNQ6uK)
[Closed all time](https://imgur.com/F6goEey)
[Opening and closing](https://imgur.com/FJP62B3)

**Output log**
Should not be much help, but here's the [log](https://pastebin.com/Q3PvEih4)

**Comment by Cairath** [comment]
Fixed with today's update
