### ISSUE TITLE
Wireless Automation Receivers not changing signal

### ISSUE THREAD

**Issue by Fortunatum** [Cairath/ONI-Mods#51]
Receivers aren't changing signal when the emitters change. They made automation switches player controlled and I know receivers are coded as a type of switch so maybe something they changed about the base class broke the way receivers are toggled?

**To Reproduce**
I made a new save with only WA activated and built an emitter receiver pair hooked up to a switch and lightbulb respectively. No matter what I do with the switch the receiver always says 'inactive' and the lightbulb won't come on.

**Output log**
The issue does not cause any crashes just not working as expected.

**Comment by Fortunatum** [comment]
I don't know if this is relevant but dupes can 'turn on' the receivers manually through a settings button in the info panel although the receivers only displays as 'active' in the info window for a split second and the wire connected doesn't actually change state. Maybe the receiver is getting to set to off every tick somehow.

**Comment by Fortunatum** [comment]
Actually neither of them light up on the top like normal so maybe the receiver is working correctly and the emitter just never updates its state correctly

**Comment by Cairath** [comment]
Thanks, I'll look into it

**Comment by Tourman36** [comment]
It's still not transmitting any signals with the latest update, and the emitters don't light up when they receive a green signal.

**Comment by Cairath** [comment]
Fixed in 6d315321b8e93b68fa46aca023e0dfa1dd00eab0

Uploaded to steam, use direct download or mod updater if steam fails to serve 2020.4.11
