### ISSUE TITLE
Obscuring of dll name

### ISSUE THREAD

**Issue by Truinto** [Cairath/ONI-Mods#53]
https://github.com/Cairath/ONI-Mods/blob/ca8adcbdd0987a8fee596bfa12a1ed01e304a010/src/Fervine/Fervine.csproj#L76

Hey, I run a mod that allows to change parameters of plants, even from other mods. For that I catch all methods that call ExtendEntityToBasicPlant and find out the Type of each method.
For your Fervine mod, the full AssemblyQualifiedName is "Fervine.FervineConfig, Fervine-merged, Version=2019.9.5.0, Culture=neutral, PublicKeyToken=null"
Now I need to load the dll into my assembly to hook into it with harmony (with Assembly.LoadFile(dll_path); ).

In any case, it seems you rename the dll when you run ILMerge. So when I search for the file "Fervine-merged.dll" I find nothing, since it's renamed to "Fervine.dll" with that post-script. I don't know what ILMerge is used for. I suspect that this rename is not needed.

For now I will simply fix the string, but obviously this doesn't hold if you make new plants or rename your mod in the future.
`if (nameDll == "Fervine-merged.dll") nameDll = "Fervine*.dll";`

Would be nice, if you could help me, by either pointing out what I could do better or being consistent with your dll name.

By the way, the mod is called "Customize Plants" and I have the source here [LINK](https://github.com/Truinto/ONI-Modloader-SimpleMods/tree/master/src/CustomizePlants)
Will push an update shortly. Also also, I have different names on all platforms, sorry for any confusion that might cause :P

**Comment by Cairath** [comment]
ILmerge is used to merge my internal library to avoid its versioning issues between mods; this is not so much as obscuring as just a temporary file name. Searching by filename isn't really a good solution to check whether a mod is installed, given they can be named anything, or further renamed by players for whatever reason.
