### ISSUE TITLE
Wireless transmitter and receiver not giving correct signals

### ISSUE THREAD

**Issue by justin-barfield** [Cairath/ONI-Mods#59]
**Describe the bug**
I have 5 transmitters and receivers in my base. The first one I made many cycles ago and it is having no issues. The 4 others I created and noticed they are not working as designed at all. The pairs are on unique channels. The transmitters appear to not be sending their signals along an "unique" channel. 

To explain:

Pair 1: Channel 0-0; Transmitter signal: Red; Receiver signal: Red
Pair 2: Channel 1-1; Transmitter signal: Red; Receiver signal: Green
Pair 1&2: Channel 0-0; Transmitter signal (original): Red; Receiver signal: Red

The receivers are receiving Green when paired with signals from a paired transmitter **except** when paired with the original transmitter. When paired with the original transmitter, the signal is registered properly.

**To Reproduce**
1. Create initial wireless pairs
2. Create secondary+ pairs
3. Secondary and onwards pairs do not receive the correct signal.

**Expected behavior**
Channel pairs to emit the same signal type

**Screenshots**
[Working pair with issue: receiver](https://github.com/justin-barfield/ONI-Mods/blob/master/receiver.png)
[Working pair with issue: transmitter](https://github.com/justin-barfield/ONI-Mods/blob/master/transmitter.png)
[Test pair channel 100](https://github.com/justin-barfield/ONI-Mods/blob/master/signal_pair.png)

**Additional context**
I am happy to assist however I can in debugging or providing more information, save data, mod file, etc.

Mod is installed using Steam subscription. Version should be up to date.

**Output log**
No game crash.

**Comment by Cairath** [comment]
Thanks, I should have time to debug tomorrow.

**Comment by Cairath** [comment]
Fixed in 6d315321b8e93b68fa46aca023e0dfa1dd00eab0

Uploaded to steam, use direct download or mod updater if steam fails to serve 2020.4.11
