### ISSUE TITLE
Sweeper extended range missing?

### ISSUE THREAD

**Issue by Thuffyr** [Cairath/ONI-Mods#60]
I click to build a new sweeper.
I see extended range.
I construct the sweeper, power it, and click on it.
I see only vanilla range, not the extended one.
and work
tried several time, all the same.
sweeper build in steel.
did I do something wrong or forgot something?
thx for help,
T.

**Comment by Cairath** [comment]
Thanks, I'll look at it soon!

**Comment by Thuffyr** [comment]
Hello Cairath,
I try to solve the issue :), bt not solved it :(
first I see that there are 3 mods on steam to increase sweeper range. Try all 3, with same results.
I check what mods I have installed, and see the customize buildings mode.
Inside by default there is the following setting> "AutoSweeperRange": 4,
I remove this line, and try again with your mode, then the others.
same result: in construction I see the extended range, after construction, normal range.
I put back the line in the customize building mod, and wrote "AutoSweeperRange": 8,
same result: I see extended range before construction, but after construction back to standard range.
Hope it will help to find a solution,
T.

**Comment by Thuffyr** [comment]
I found the issue... in the new update of customize building, there is a slider use t set the range... working without your mod so... thx for it anyway and you can close the issue.
T.
