### ISSUE TITLE
Double Sweeper Range - Range behaves weird

### ISSUE THREAD

**Issue by Yaslana** [Cairath/ONI-Mods#74]
**Describe the bug**
My sweepers have only their normal range. The weird thing: I have "Show Building Ranges" mod installed and when I place the blueprint it shows me the modded ranges, but after my dups build the sweeper it reverts to its vanilla range. In what range is shown AND in what stuff they can actually reach. This is not just a visible error of "show building ranges", they cannot reach stuff outside their vanilla range. I DO have the mod installed and activated ;)

**To Reproduce**
1. place blueprint (range is big)
2. wait until build
3. check range (range is small)

**Expected behavior**
Sweeper should have double reach.

**Screenshots**
![dsr1](https://user-images.githubusercontent.com/56886614/89719827-9c79b880-d9cc-11ea-9218-0075eb783675.png)
![dsr2](https://user-images.githubusercontent.com/56886614/89719828-9d124f00-d9cc-11ea-80ee-4a1b36faee1e.png)
![dsr3](https://user-images.githubusercontent.com/56886614/89719829-9daae580-d9cc-11ea-8cbf-3b4712e3d983.png)

**Additional context**
Nothing I know of.

**Output log**
No crashes.

**Comment by RiabokinSergii** [comment]
Hello!
I have this problem too, when I select this, all work fine but after build I see normal size.
Please update this mod.
I have game version AP-420700-D Automation Pack.
Thanks.

**Comment by tajemniktv** [comment]
Hi,
the issue still persists. If any more information is needed let me know.

**Comment by etmoonshade** [comment]
I'll third this bug report, though it's from quite a few months ago - I'm seeing the same thing on build U39-490405-5 w/ the DLC.

This is actually the same behavior I'm getting from another mod that doubles sweeper range as well - probably something that got mucked up during some sort of update. :)

**Comment by Cairath** [comment]
i'm very late :P but still appears to work fine when tested.

**Comment by vikoalucard** [comment]
Hello, I still have this now, exactly as described. The original range is displayed after it's been placed, the upgraded range never really works, it's just displayed before building.
