### ISSUE TITLE
Notification trigger not functional

### ISSUE THREAD

**Issue by LennyIndustries** [Cairath/ONI-Mods#90]
The pencil icon is not visible on the notification trigger and can't be renamed so it does not show a notification.

1. install mod
2. start game
3. build notification trigger
4. open notification trigger menu
5. no pencil icon is visible

A pencil icon to rename the notification trigger.

![Notification trigger](https://user-images.githubusercontent.com/10868197/115774550-06e35500-a3b2-11eb-8453-1fd28b295b41.PNG)

**Comment by Cairath** [comment]
a bit late, but the mod's been deprecated due to the notification alarm being incorporated into the game
