### ISSUE TITLE
Bigger Building Menu (DLC)—Notifications and alerts are on top of the building menu

### ISSUE THREAD

**Issue by Xirema** [Cairath/ONI-Mods#92]
**Description**
When a building menu is big enough, especially in the case of the Base or Automation build menus, the box extends past the space where Notifications are populated, which are on a nearer UI layer than the building menu. This means that options behind the notifications cannot be selected and attempts to select items partially obscured is tricky.

**To Reproduce**
1. Open a Building Menu with a large number of buildings (may need to turn on sandbox mode or open a save with most of the research complete
2. Attempt to select one of the top building options, like a ladder or Fire Poll
3. Those options are obscured by the colony notifications

**Expected behavior**
Either the Building Menu needs to be shrunk a little so as not to reach all the way to the notifications, or (if possible) it needs to be put on a UI layer in front of the notifications

**Screenshots**
![image](https://user-images.githubusercontent.com/1447761/119743121-ca8e9300-be4e-11eb-8007-6a3f4c8b2265.png)

**Comment by Cairath** [comment]
You can use the mod's config (see mod description on steam) to select how many max rows you want. Changing UI layering is something not easily done/something I will pursue
