### ISSUE TITLE
Lights Out Mod - Edits to Config.json have no effect.

### ISSUE THREAD

**Issue by Crazz2424** [Cairath/ONI-Mods#96]
**This was reported in Steam comments but properly reporting here. 

Changes to the Config.json file have no effect. It acts as if the file does not exist so all my games are too dark. Tried on my PC and Laptop. I just wanted to make the overall darkness brighter. (Screen brightness is maxed) I have the latest version of the mod and followed the instructions creating a copy and renaming it Config.json. I set the following in the json file but notice no difference.

//The lowest brightness of the world's darkness. 0 = fully black. 255 = normal lighting
"LowestFog": 150,

//Whether dupe emits light around it (range: 3). Values: true or false (LOWERCASE!)
"DupeLight": true,

//If true, how much lux should the dupe emit. Keep in mind this does affect actual brightness so adjust the buff thresholds.
"DupeLightLux": 200,

**Comment by Cairath** [comment]
First, use Mod Updater and verify the issue still exists. I fixed and tested that with the recent mod update. If issue still persists, provide the game log file - C:\Users\%username%\AppData\LocalLow\Klei\Oxygen Not Included\Player.log

**Comment by Crazz2424** [comment]
OK, I installed and ran Mod Updater on the mod. It did say (along with 7 other mods) that it was out of date. I redid the steps to create the Config.json file by copying the template file, renaming it and only made two adjustments but it is still very dark. As a test I disabled all mods except Lights out and mod loader and had the same result.

[Player.log](https://github.com/Cairath/ONI-Mods/files/6760413/Player.log)

//The highest brightness of the world's darkness. 0 = fully black. 255 = normal lighting
    "HighestFog": 255,

//Whether dupe emits light around it (range: 3). Values: true or false (LOWERCASE!)
    "DupeLight": true,

**Comment by Cairath** [comment]
Alriiiight you are using legacy vanilla. Please place the config file in ...Documents\Klei\OxygenNotIncluded\mods\Steam\1860377458\archived_versions\vanilla\Config.json

I forgot to change that to always use the root folder despite loading an older version of the mod. I am reworking the config system so that will be fixed when I am done with that. Let me know if putting the config file in the location above works

**Comment by Crazz2424** [comment]
Yes sir, that worked thank you!
