### ISSUE TITLE
Mod "Plan Buildings Without Materials" shows "Mod out of date" since July 16th Breath of Fresh Air Update

### ISSUE THREAD

**Issue by strudo76** [Cairath/ONI-Mods#99]
**Describe the bug**
The mod "Plan Buildings Without Materials" shows as "Mod out of date" when playing with the DLC disabled.

**To Reproduce**
Load game with mod subscribed and DLC disabled and open the mod manager

**Expected behavior**
Mod able to be enabled

**Screenshots**

**Additional context**
I have not attempted to use the mod while the DLC is active.

**Output log**
If applicable (game crashes or displays errors) please copy and paste part of the output_log.txt game file that contains information about the crash/error.

**Comment by Cairath** [comment]
A bit late on commenting, but the mod's been updated
